// pendragon-npcs.js  —  Auto-generated from spreadsheet Year 489
// DO NOT EDIT MANUALLY — regenerate from Links___Chars spreadsheet

const SPREADSHEET_NPCS = [
  {id:1,
    name:"Count Roderick",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"41",
    glory:"8840",
    pronoun:"He/him",
    family:"Sarum [Salisbury]",
    misc:"Player Knights Leige, Suspicious of Silchester, Sir Blains is his rival Baron of Castle of the Rock (Salisbury), Borders, Vagon, DuPlain, Roe Deer Ford (Thamesmouth), Kingstown (Hartland), Cockfield (Caercolun), Wildspring (Caerwent). Default lord of Player-knights.",
    playerVisible:true},
  {id:2,
    name:"Countess Ellen",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"25",
    glory:"2720",
    pronoun:"She/her",
    family:"Sarum [Salisbury]",
    misc:"Countess of Salisbury. Competent noblewoman from Marlboro. Lord: Earl of Salisbury. Home: Sarum Castle. Woman's Gift: Good with animals. SIZ:12 DEX:14 STR:12 CON:17 APP:9 HP:29. Stewardship 16, Intrigue 12, Courtesy 17.",
    playerVisible:true},
  {id:3,
    name:"Lady Jenna",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"7",
    pronoun:"She/her",
    family:"Sarum [Salisbury]",
    misc:"not yet marriageable Daughter of Count Roderick and Countess Ellen\nWoman's Gift: Soothes animals and crying children alike",
    stats:"Modest 16 · Love (Family) · Dancing 16 · Courtesy 14",
    playerVisible:true},
  {id:4,
    name:"Sir Elad",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"51",
    glory:"6189",
    pronoun:"He/him",
    family:"Vagon",
    misc:"Salisbury Marshall",
    stats:"Just 13 · Loyalty (Roderick) · Battle 16 · Heraldry 21",
    playerVisible:true},
  {id:5,
    name:"Sir Hywel",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"48",
    glory:"6457",
    pronoun:"He/him",
    family:"West Lavington",
    misc:"has a young daughter, refuses to re-marry",
    stats:"Valorous 15 · Love (Daughter) · Hunting 18 · Sword 11",
    playerVisible:true},
  {id:6,
    name:"Sir Jarren",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"29",
    glory:"3190",
    pronoun:"He/him",
    family:"Berwick St. James",
    misc:"Best swordsman of Roderick's court",
    stats:"Energetic 12 · Love (Glory) · Sword 16 · Tourney 15",
    playerVisible:true},
  {id:7,
    name:"Sir Amig",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"51",
    glory:"7234",
    pronoun:"He/him",
    family:"Tilshead",
    misc:"Scarred, veteran of many battles. Castelan of Tilshead",
    stats:"Prudent 16 · Hate (Saxons) · Battle 21 · Awareness 20",
    playerVisible:true},
  {id:8,
    name:"Sir Bles",
    role:"Knight",
    faction:"Salisbury",
    status:"dead",
    pronoun:"He/They",
    misc:"RIP father to Lady Adwen",
    stats:"Valorous 15 · Love (Lady Adwen) · Sword 18 · Lance 13",
    playerVisible:true},
  {id:9,
    name:"Lady Elaine",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"30",
    glory:"1258",
    pronoun:"She/her",
    misc:"Elligible in Sarum, scandalously unfaithful\nWoman's Gift: Reads a room instantly — knows who desires whom",
    stats:"Lustful 17 · Love (Romance) · Flirting 16 · Intrigue 14",
    playerVisible:true},
  {id:10,
    name:"Lady Veneranda",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"9",
    pronoun:"She/her",
    family:"Sarum [Salisbury]",
    misc:"Daughter of Sir Amig\nWoman's Gift: Remembers every face she has ever seen",
    stats:"Trusting 14 · Love (Family) · Courtesy 11 · Dancing 14",
    playerVisible:true},
  {id:11,
    name:"Lady Calire",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"21",
    glory:"420",
    pronoun:"She/her",
    family:"Vagon",
    misc:"Daughter of Sir Elad\nWoman's Gift: Calms heated arguments with a single word",
    stats:"Generous 15 · Love (Father) · Stewardship 17 · Courtesy 16",
    playerVisible:true},
  {id:12,
    name:"Bishop Roger",
    role:"Priest",
    faction:"Salisbury",
    status:"alive",
    pronoun:"He/him",
    misc:"Bishop of Salisbury, tends towards the practical",
    stats:"Just 18 · Honor · Orate 14 · Intrigue 15",
    playerVisible:true},
  {id:13,
    name:"Father Tewi",
    role:"Priest",
    faction:"Salisbury",
    status:"dead",
    pronoun:"He/him",
    misc:"Priest of Salisbury Castle, likes to drink, maybe wandering eye to castle staff",
    stats:"Indulgent 18 · Love (Wine) · Folklore 17 · First Aid 16",
    playerVisible:true},
  {id:14,
    name:"Syr Ricerch",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"30",
    glory:"1780",
    pronoun:"He/him",
    misc:"Former Holder of Shrewton for Adwen now in Rodericks court",
    stats:"Forgiving 16 · Loyalty (Roderick) · Sword 16 · Courtesy 14",
    playerVisible:true},
  {id:15,
    name:"Sir Gdarn",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"25",
    glory:"2050",
    pronoun:"He/him",
    family:"Berwick St. James",
    misc:"ugly facial scar (-2 APP) and ugly (-3 APP) and stonefaced, inscrutable",
    playerVisible:true},
  {id:16,
    name:"Sir Caerau",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"26",
    glory:"2100",
    pronoun:"He/him",
    family:"Woodford",
    misc:"abusive to servants and avid gambler and master of elocution and rhetoric, Liege’s bastard as squire\nget an allowance of 2£",
    stats:"Arbitrary 12 · Love (Gambling) · Gaming 14 · Orate 16",
    playerVisible:true},
  {id:17,
    name:"Sir Gareth",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"26",
    glory:"2500?",
    pronoun:"He/him",
    family:"Winterbourne Stoke",
    misc:"He is cautious but nervous.",
    stats:"Prudent 18 · Honor · Lance 14 · Horsemanship 14",
    playerVisible:true},
  {id:18,
    name:"Sir Padern",
    role:"Knight",
    faction:"Salisbury",
    status:"alive",
    age:"30",
    glory:"3700",
    pronoun:"He/him",
    family:"Wylye",
    misc:"They are a bit of a hedonist and their goal is peace, Lost a horse",
    stats:"Temperate 18 · Love (Peace) · Orate 21 · Courtesy 16",
    playerVisible:true},
  {id:19,
    name:"Sir Gwanon",
    role:"Squire",
    faction:"Salisbury",
    status:"alive",
    age:"25",
    glory:"2500",
    stats:"Energetic 20 · Loyalty (Roderick) · Horsemanship 16 · Sword 17",
    playerVisible:true},
  {id:20,
    name:"Gorthyn",
    role:"Squire",
    faction:"Salisbury",
    status:"alive",
    age:"21",
    glory:"250",
    pronoun:"He/Him",
    family:"Bastard of Sir Roderik Squire of Sir Caerau",
    misc:"Let the armour of Careau Rust",
    stats:"Trusting 15 · Loyalty (Sir Caerau) · Horsemanship 16 · Awareness 21",
    playerVisible:true},
  {id:21,
    name:"Lady Indeg",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"36",
    glory:"2500",
    pronoun:"She/her",
    misc:"Proud",
    stats:"2 efoeffed manors, $2 extra per year, 14/glory a year.",
    playerVisible:true},
  {id:22,
    name:"Lady Adwen",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"22",
    glory:"740",
    pronoun:"She/her",
    family:"Gwegon",
    misc:"Wife of Gwegon (PC). Brought Shrewton & Allington manors.\nWoman's Gift: Never forgets a slight against her husband — patient, but keeps score",
    stats:"Generous 16 · Love (Gwegon) · Stewardship 18 · First Aid 12",
    playerVisible:true},
  {id:23,
    name:"Lady Gwiona",
    role:"Steward",
    faction:"Salisbury",
    status:"alive",
    age:"24",
    glory:"856",
    pronoun:"She/her",
    family:"Agragan",
    misc:"Wife of Agragan (PC). Brought Horton and Tisbury manors.\nWoman's Gift: Green thumb — her gardens yield more than neighbours'",
    stats:"Modest 13 · Love (Agragan) · Stewardship 16 · Courtesy 12",
    playerVisible:true},
  {id:24,
    name:"Sir Duach",
    role:"Baron",
    faction:"Salisbury",
    status:"alive",
    misc:"Baron of Wereside (Salisbury).",
    stats:"Valorous 20 · Loyalty (Roderick) · Battle 14 · Sword 19",
    playerVisible:true},
  {id:25,
    name:"Dilwyn",
    role:"Abbot",
    faction:"Salisbury",
    status:"alive",
    misc:"Abbot of Ambrius Abbey (Salisbury). Baron of the Robe.",
    stats:"Spiritual 19 · Honor · Orate 15 · Folklore 14",
    playerVisible:true},
  {id:26,
    name:"King Uther Pendragon",
    role:"King",
    faction:"Uthers Court",
    status:"alive",
    age:"51",
    glory:"27750",
    pronoun:"He/Him",
    misc:"King of Logres, wants to be High King of all Britain. In 488 stayed behind while Madoc led the army to France; deeply suspicious of Duke Gorlois, whom he calls the primary culprit, and wary of threats on multiple fronts.",
    stats:"Proud 17 · Love (Ygraine) · Battle 19 · Orate 18",
    playerVisible:true},
  {id:27,
    name:"Prince Madoc",
    role:"Prince of Logres",
    faction:"Uthers Court",
    status:"alive",
    age:"21",
    glory:"3228",
    pronoun:"He/him",
    misc:"Son and heir of Uther. Led the British army to Frankland in 488. Refused Praetor Syagrius's plea to march on Rouen, declaring 'I am not my father.' A decisive, independent commander beginning to forge his own identity.",
    stats:"Just 18 · Loyalty (Britain) · Battle 18 · Sword 14",
    playerVisible:true},
  {id:28,
    name:"Merlin the Magician",
    role:"Druid",
    faction:"Uthers Court",
    status:"alive",
    glory:"14452",
    stats:"Prudent 16 · Love (The Plan) · Faerie Lore 14 · Orate 11",
    playerVisible:true},
  {id:29,
    name:"Brother Canagus",
    role:"Almoner, Russet Monk",
    faction:"Uthers Court",
    status:"alive",
    age:"20",
    glory:"0",
    pronoun:"He/him",
    stats:"Merciful 17 · Hospitality · First Aid 17 · Folklore 18",
    playerVisible:true},
  {id:30,
    name:"Sir Bellias",
    role:"Bodyguard, Captain of Guard",
    faction:"Uthers Court",
    status:"alive",
    age:"41",
    glory:"8439",
    pronoun:"He/him",
    stats:"Valorous 14 · Loyalty (Uther) · Sword 18 · Awareness 18",
    misc:"Enemy of Agragan (PC) — mutual hate since 489. Probably insulted by Agragan.",
    playerVisible:true},
  {id:31,
    name:"Sir Diocenar",
    role:"Butler, Vassal Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"42",
    glory:"3222",
    pronoun:"He/him",
    stats:"Temperate 17 · Honor · Stewardship 16 · Courtesy 16",
    playerVisible:true},
  {id:32,
    name:"Abbot John",
    role:"Chancellor, Black Monk",
    faction:"Uthers Court",
    status:"alive",
    age:"50",
    glory:"0",
    pronoun:"He/him",
    stats:"Spiritual 20 · Honor · Orate 18 · Intrigue 13",
    playerVisible:true},
  {id:33,
    name:"Brother Hugh",
    role:"Chamberlain, Black Monk",
    faction:"Uthers Court",
    status:"alive",
    age:"33",
    glory:"0",
    pronoun:"He/him",
    stats:"Modest 16 · Loyalty (Uther) · Courtesy 15 · Stewardship 16",
    playerVisible:true},
  {id:34,
    name:"Abner",
    role:"Cofferer",
    faction:"Uthers Court",
    status:"alive",
    age:"37",
    glory:"0",
    pronoun:"He/him",
    stats:"Honest 18 · Honor · Stewardship 16 · Awareness 15",
    playerVisible:true},
  {id:35,
    name:"Sir Eliezier/Sir Argan",
    role:"The Constable",
    faction:"Uthers Court",
    status:"alive",
    stats:"Energetic 18 · Loyalty (Uther) · Battle 20 · Horsemanship 16",
    playerVisible:true},
  {id:36,
    name:"Sir Llywarch",
    role:"Deputy Constable, Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"42",
    glory:"3928",
    pronoun:"He/him",
    stats:"Just 14 · Loyalty (Uther) · Lance 16 · Heraldry 15",
    misc:"Hidden enemy of Mellyr (PC) since 489 court. Mellyr does not know he is hated.",
    playerVisible:true},
  {id:37,
    name:"Father Lucius / Teacher Padern",
    role:"The Confessors",
    faction:"Uthers Court",
    status:"alive",
    stats:"Spiritual 17 · Honor · Orate 14 · First Aid 13",
    playerVisible:true},
  {id:38,
    name:"Sir Sadinal",
    role:"Dapifer and Herald, Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"38",
    glory:"7632",
    pronoun:"He/him",
    stats:"Proud 14 · Love (Glory) · Heraldry 12 · Orate 15",
    playerVisible:true},
  {id:39,
    name:"Sir Do de Carduel",
    role:"Forest Justiciar, Vassal Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"29",
    glory:"4531",
    pronoun:"He/him",
    stats:"Energetic 16 · Loyalty (Uther) · Hunting 14 · Awareness 16",
    playerVisible:true},
  {id:40,
    name:"Sir Brychan",
    role:"The Deputy Marshall",
    faction:"Uthers Court",
    status:"alive",
    age:"35",
    glory:"5867",
    pronoun:"He/him",
    stats:"Valorous 17 · Loyalty (Uther) · Battle 18 · Lance 14",
    playerVisible:true},
  {id:41,
    name:"Sir Yvo",
    role:"Royal Standard Bearer, Vassal Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"54",
    glory:"22853",
    pronoun:"He/him",
    stats:"Proud 19 · Love (Glory) · Heraldry 15 · Battle 20",
    playerVisible:true},
  {id:42,
    name:"Lady Dyanne",
    role:"",
    faction:"Uthers Court",
    status:"alive",
    misc:"Woman's Gift: Puts strangers at ease — enemies share secrets with her by the second cup",
    stats:"Generous 17 · Hospitality · Dancing 18 · Courtesy 19",
    playerVisible:true},
  {id:43,
    name:"Lady Wynflaeth",
    role:"",
    faction:"Uthers Court",
    status:"alive",
    misc:"Woman's Gift: Senses when someone is hiding grief",
    stats:"Trusting 18 · Love (Arianwen, lost) · Intrigue 18 · Courtesy 14",
    playerVisible:true},
  {id:44,
    name:"Lady Anne",
    role:"",
    faction:"Uthers Court",
    status:"alive",
    playerVisible:true},
  {id:45,
    name:"Lady Harley",
    role:"",
    faction:"Uthers Court",
    status:"alive",
    misc:"Woman's Gift: Sets court trends — what she wears, others scramble to copy",
    stats:"Worldly 13 · Love (Fashion) · Fashion 13 · Flirting 15",
    playerVisible:true},
  {id:46,
    name:"Lady Marigold",
    role:"",
    faction:"Uthers Court",
    status:"alive",
    playerVisible:true},
  {id:47,
    name:"Sir Gracian",
    role:"Commander of the Watch",
    faction:"Uthers Court",
    status:"alive",
    age:"39",
    glory:"2947",
    pronoun:"He/him",
    stats:"Suspicious 16 · Honor · Awareness 16 · Sword 11",
    playerVisible:true},
  {id:48,
    name:"Sir Canet of Occire",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    glory:"1459",
    pronoun:"He/him",
    stats:"Trusting 21 · Love (Glory) · Courtesy 12 · Lance 11",
    playerVisible:true},
  {id:49,
    name:"Sir Felix",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    glory:"4300",
    pronoun:"He/him",
    stats:"Energetic 13 · Love (Glory) · Sword 16 · Tourney 18",
    playerVisible:true},
  {id:50,
    name:"Melion esq.",
    role:"Chief of Stables",
    faction:"Uthers Court",
    status:"alive",
    glory:"2321",
    pronoun:"He/him",
    stats:"Honest 15 · Love (Horses) · Horsemanship 16 · First Aid 20",
    playerVisible:true},
  {id:51,
    name:"Sir Moneval",
    role:"Royal Bouncer, Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"32",
    glory:"2468",
    pronoun:"He/him",
    stats:"Cruel 18 · Loyalty (Uther) · Sword 15 · Awareness 15",
    playerVisible:true},
  {id:52,
    name:"Sir Minodos",
    role:"Twin Thug, Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"27",
    glory:"2468",
    pronoun:"He/him",
    stats:"Cruel 11 · Loyalty (Uther) · Spear 19 · Sword 16",
    playerVisible:true},
  {id:53,
    name:"Sir Minodalis",
    role:"Twin Thug, Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"27",
    glory:"2468",
    pronoun:"He/him",
    stats:"Cruel 17 · Loyalty (Uther) · Sword 16 · Dagger 21",
    playerVisible:true},
  {id:54,
    name:"Sir Heliandor de la Montagne",
    role:"Household Knight (The Trio)",
    faction:"Uthers Court",
    status:"alive",
    age:"44",
    glory:"3338",
    pronoun:"He/him",
    stats:"Valorous 16 · Loyalty (Uther) · Spear 14 · Battle 18",
    playerVisible:true},
  {id:55,
    name:"Sir Canuc de Caerec",
    role:"Household Knight (The Trio)",
    faction:"Uthers Court",
    status:"alive",
    age:"32",
    glory:"2665",
    pronoun:"He/him",
    stats:"Reckless 12 · Loyalty (Uther) · Sword 13 · Dagger 18",
    playerVisible:true},
  {id:56,
    name:"Sir Carac",
    role:"Household Knight (The Trio)",
    faction:"Uthers Court",
    status:"alive",
    age:"37",
    glory:"2341",
    pronoun:"He/him",
    stats:"Vengeful 15 · Loyalty (Uther) · Sword 14 · Spear 15",
    playerVisible:true},
  {id:57,
    name:"Sir Eliezier the Strong",
    role:"Constable, Household Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"41",
    glory:"8248",
    pronoun:"He/him",
    stats:"Energetic 14 · Honor · Horsemanship 15 · Battle 16",
    playerVisible:true},
  {id:58,
    name:"Father Lucius",
    role:"Confessor, Roman Church",
    faction:"Uthers Court",
    status:"alive",
    glory:"0",
    pronoun:"He/him",
    stats:"Spiritual 15 · Honor · Orate 12 · First Aid 15",
    playerVisible:true},
  {id:59,
    name:"Teacher Padern \"the Knee\"",
    role:"Confessor, British Church",
    faction:"Uthers Court",
    status:"alive",
    glory:"0",
    pronoun:"He/him",
    stats:"Spiritual 17 · Honor · Orate 15 · Awareness 12",
    playerVisible:true},
  {id:60,
    name:"Sir Gwyllim",
    role:"Constable of White Tower, Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"41",
    glory:"7884",
    pronoun:"He/him",
    stats:"Prudent 14 · Loyalty (Uther) · Sword 16 · Awareness 16",
    playerVisible:true},
  {id:61,
    name:"Ralf",
    role:"Huntsman",
    faction:"Uthers Court",
    status:"alive",
    age:"28",
    glory:"0",
    pronoun:"He/him",
    stats:"Energetic 19 · Love (The Hunt) · Hunting 20 · Awareness 21",
    playerVisible:true},
  {id:62,
    name:"Brother Baucillias",
    role:"Physician, Russet Monk",
    faction:"Uthers Court",
    status:"alive",
    glory:"0",
    pronoun:"He/him",
    stats:"Merciful 15 · Honor · First Aid 14 · Folklore 12",
    playerVisible:true},
  {id:63,
    name:"Sir Gaudifier",
    role:"Cupbearer, Household Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"45",
    glory:"3428",
    pronoun:"He/him",
    stats:"Generous 20 · Hospitality · Courtesy 15 · Intrigue 18",
    playerVisible:true},
  {id:64,
    name:"Sir Goreau",
    role:"Seneschal, Household Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"38",
    glory:"5259",
    pronoun:"He/him",
    stats:"Just 11 · Loyalty (Uther) · Stewardship 18 · Intrigue 19",
    playerVisible:true},
  {id:65,
    name:"Sir Geraint",
    role:"Seneschal (later), Baron of Guinnon",
    faction:"Uthers Court",
    status:"alive",
    age:"32",
    glory:"6347",
    misc:"Sir Geraint, Baron and Officer. Glory 6347 (Renowned), Age 32 in 480. Appearance: Tall, rangy. Personality: Stern. Type: Administrator. Notable: Energetic 16, Prudent 17, Just 16, Stewardship 19. Baron of Guinnon (Caercolun). Plain-looking, plain-speaking, dutiful and stern.",
    playerVisible:true},
  {id:66,
    name:"Sir Caradoc",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"44",
    glory:"11284",
    misc:"Sir Caradoc the Thirteenth. Household Knight. Glory 11284 (Famous), Age 44 in 480. Appearance: Gigantic. Personality: Jealous, hostile. Type: Adventurer. Notable: SIZ 20, Proud 20, Vengeful 16, Homage (Uther) 23, Spear Expertise 24. Huge, strong, fanatically loyal to Uther; jealous of his position. Prone to fits of rage when crossed; hostile towards court newcomers. Opinions nearly impossible to change.",
    playerVisible:true},
  {id:67,
    name:"Sir Argan",
    role:"King's Constable",
    faction:"Uthers Court",
    status:"alive",
    age:"29",
    glory:"5648",
    misc:"Sir Argan ap Maelgad. King's Constable / Household Knight. Glory 5648 (Renowned), Age 29 in 480. Appearance: Strong. Personality: Grim, efficient. Type: Combatant, diplomat. Notable: Energetic 16, Vengeful 18, Homage (Uther) 17, Diplomacy 17, Horsemanship 18, Sword 21. Uther's fixer; travels all over Logres eliminating problems using any means necessary. Close friend of Sir Galehaut the Brown. Fair hair, blue eyes, full bushy beard. Will lose left ear fighting rebellious King of Bedegraine. Married to Dyagenne. Later builds Uther's Shame castle and harasses Uther's knights for decades.",
    playerVisible:true},
  {id:68,
    name:"Sir Canet",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    glory:"1459",
    misc:"Sir Canet of Occire, Household Knight. Glory 1459 (Unproven). Notable: Courtesy 12. Young, eager knight happy to associate with anyone more experienced. Blabs anything to please the asking knight.",
    playerVisible:true},
  {id:69,
    name:"Melion",
    role:"Chief of Stables",
    faction:"Uthers Court",
    status:"alive",
    glory:"2321",
    misc:"Melion, esq., Chief of Stables. Glory 2321 (Respected). Notable: Courtesy 10, Horsemanship 16. Always at the royal stable. Will lend a horse, take one in, or otherwise be the recognisable stable contact for Player-knights. Doesn't talk much — except about horses.",
    playerVisible:true},
  {id:70,
    name:"Sir Heliandor",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"44",
    glory:"3338",
    misc:"Sir Heliandor de la Montagne, Household Knight (The Trio). Glory 3338 (Notable), Age 44 in 480. Appearance: Broad-shouldered. One of Uther's three favourite thugs. Big, mean on command, experienced, brutally cruel. Sit in front of Uther at feasts, fight beside him on battlefield. Kill only on command.",
    playerVisible:true},
  {id:71,
    name:"Sir Canuc",
    role:"Household Knight",
    faction:"Uthers Court",
    status:"alive",
    age:"32",
    glory:"2665",
    misc:"Sir Canuc de Caerec, Household Knight (The Trio). Glory 2665 (Respected), Age 32 in 480. Appearance: Tall and rangy, piercing eyes. One of Uther's three favourite thugs. Stupid, brutish. Fighter. Notable: Spear Expertise, Sword, Dagger 21.",
    playerVisible:true},
  {id:72,
    name:"Sir Eliezier",
    role:"Constable, Household Officer",
    faction:"Uthers Court",
    status:"alive",
    age:"41",
    glory:"8248",
    misc:"Sir Eliezier the Strong, Constable (Household, Officer). Glory 8248 (Famous), Age 41 in 480. Appearance: Powerful. Personality: Moody. Type: Administrator. Notable: Energetic 18, Horsemanship 22, Spear Expertise 20, Sword 18. Renowned mighty knight with astonishing horsemanship; claimed to speak to horses. Has tamed near-wild horses in one session to complete obedience.",
    playerVisible:true},
  {id:73,
    name:"Teacher Padern",
    role:"Confessor, British Church",
    faction:"Uthers Court",
    status:"alive",
    glory:"0",
    misc:"Teacher Padern 'the Knee', Confessor, Ordained Teacher (priest) in British Church. Appearance: Powerful. Personality: Hair-trigger temper. Notable: DEX 17, Priest (British Christian) 6. One of Uther's two confessors — fights Father Lucius barehanded (Lucius STR vs Padern DEX) for the right to hear the confession; winner absolves the king and explains why it wasn't really a sin.",
    playerVisible:true},
  {id:74,
    name:"Lady Elin",
    role:"Countess",
    faction:"Rydychan",
    status:"alive",
    glory:"3900",
    misc:"Woman's Gift: Unshakeable composure — never seen to weep in public",
    stats:"Proud 12 · Love (Rydychan) · Intrigue 15 · Stewardship 12",
    playerVisible:false},
  {id:75,
    name:"Arianwen",
    role:"Lady",
    faction:"Rydychan",
    status:"unknown",
    age:"20",
    glory:"?",
    pronoun:"She/her",
    misc:"Uthers Court Lady Wynflaeth ist looking for her\nWoman's Gift: Finds things that are lost — people, objects, paths",
    stats:"Trusting 15 · Love (Family, lost) · Dancing 17 · Courtesy 14",
    playerVisible:false},
  {id:76,
    name:"Sir Gwythyr",
    role:"Baron",
    faction:"Rydychan",
    status:"alive",
    misc:"Baron of Oxenford (Rydychan).",
    stats:"Suspicious 16 · Loyalty (Lady Elin) · Battle 19 · Sword 15",
    playerVisible:true},
  {id:77,
    name:"Sir Blains",
    role:"Knight",
    faction:"Silchester",
    status:"alive",
    age:"33",
    family:"Levcomagus [Silchester]",
    misc:"Rival of Roderick, favorite of Ulfius",
    stats:"Selfish 14 · Love (Glory) · Sword 20 · Intrigue 19",
    playerVisible:false},
  {id:78,
    name:"Ulfius",
    role:"Duke",
    faction:"Silchester",
    status:"alive",
    age:"40",
    glory:"9.224",
    family:"Silchester",
    misc:"Good friend and close ally to Uther, Marshall of Logres",
    stats:"Energetic 15 · Loyalty (Uther) · Battle 17 · Orate 18",
    playerVisible:false},
  {id:79,
    name:"Sir Staterius",
    role:"Baron",
    faction:"Silchester",
    status:"alive",
    misc:"Baron of Thornbush Castle (Silchester).",
    stats:"Prudent 14 · Honor · Heraldry 15 · Sword 21",
    playerVisible:true},
  {id:80,
    name:"Valerius",
    role:"Abbot",
    faction:"Silchester",
    status:"alive",
    misc:"Abbot of Riverford Abbey, Lord of Riverford (Silchester). Baron of the Robe.",
    stats:"Spiritual 16 · Honor · Orate 13 · Stewardship 14",
    playerVisible:true},
  {id:81,
    name:"Metellus",
    role:"Bishop",
    faction:"Silchester",
    status:"alive",
    misc:"Bishop of Silchester (Silchester). Baron of the Robe.",
    stats:"Just 19 · Honor · Orate 11 · Intrigue 16",
    playerVisible:true},
  {id:82,
    name:"Canan",
    role:"King of Estragales",
    faction:"Estragales",
    status:"alive",
    age:"52",
    family:"Estragales",
    stats:"Temperate 17 · Love (Estragales) · Battle 14 · Intrigue 12",
    playerVisible:false},
  {id:83,
    name:"Didac",
    role:"Heir of Estragelas",
    faction:"Estragales",
    status:"alive",
    age:"27",
    stats:"Valorous 15 · Loyalty (Canan) · Lance 15 · Sword 20",
    playerVisible:false},
  {id:84,
    name:"Gundemar",
    role:"Advisor",
    faction:"Estragales",
    status:"alive",
    age:"43",
    stats:"Prudent 17 · Love (Lunet) · Intrigue 20 · Courtesy 16",
    playerVisible:false},
  {id:85,
    name:"Lunet",
    role:"Daughter of Gundemar",
    faction:"Estragales",
    status:"alive",
    age:"21",
    misc:"APP",
    playerVisible:false},
  {id:86,
    name:"Edar",
    role:"Brother of Lunet",
    faction:"Estragales",
    status:"alive",
    stats:"Energetic 17 · Loyalty (Gundemar) · Hunting 16 · Sword 14",
    playerVisible:false},
  {id:87,
    name:"Leget",
    role:"Hill Tribe Leader",
    faction:"Estragales",
    status:"alive",
    age:"40",
    glory:"200",
    pronoun:"He/him",
    stats:"Valorous 11 · Hate (Estragales nobility) · Awareness 20 · Sword 14",
    playerVisible:false},
  {id:88,
    name:"Nanteleod",
    role:"",
    faction:"Estragales",
    status:"alive",
    glory:"6522",
    misc:"King of Escavalon. Brave, vigorous; wants to drive Saxons out. Temperate, suspicious, honourable. No lord. SIZ:5 DEX:14 STR:9 CON:15 APP:10 HP:20. Battle 22, Sword 20, Lance 19. Glory 6522.",
    playerVisible:false},
  {id:89,
    name:"Sir Pellinore",
    role:"King of Norgales",
    faction:"Norgales",
    status:"alive",
    age:"35",
    glory:"11923",
    pronoun:"Listeneise",
    family:"Yes",
    misc:"King of the Isles. Obsessed with hunting the Questing Beast. A peerless jouster.",
    stats:"Valorous 17 · Love (Questing Beast) · Hunting 17 · Lance 14",
    playerVisible:false},
  {id:90,
    name:"Gorlois",
    role:"Duke",
    faction:"Cornwall",
    status:"alive",
    age:"52",
    glory:"11.914",
    misc:"Duke of Cornwall (County of Logres). In 488, Cornwall ignored the king's summons to war in France — court gossip calls this a direct insult. Uther considers him his primary political threat.",
    stats:"Proud 21 · Hate (Uther) · Battle 17 · Sword 16",
    playerVisible:false},
  {id:91,
    name:"Ygraine",
    role:"",
    faction:"Cornwall",
    status:"alive",
    misc:"Wife of Duke Gorlois\nWoman's Gift: Her beauty inspires extraordinary deeds — men act beyond their nature in her presence",
    stats:"Honest 11 · Love (Gorlois) · Courtesy 19 · Intrigue 13",
    playerVisible:false},
  {id:92,
    name:"Cador",
    role:"",
    faction:"Cornwall",
    status:"alive",
    glory:"7119",
    misc:"Mercenary Captain. Wandering knight, served Gorlois faithfully. Energetic, just, pious, brave. No lord (loyal to paymaster). Suspicious of Idres +5. SIZ:10 DEX:16 STR:16 CON:22 APP:8 HP:32. Battle 16, Sword 16, Lance 21, Horsemanship 18. Hate Saxons 15.",
    playerVisible:false},
  {id:93,
    name:"Idres",
    role:"Knight",
    faction:"Cornwall",
    status:"alive",
    age:"32",
    glory:"4200",
    pronoun:"He/him",
    family:"Cornwall",
    misc:"King of Garlot/Cornwall. A key ally/vassal to Gorlois",
    stats:"Energetic 13 · Loyalty (Gorlois) · Battle 17 · Sword 14",
    playerVisible:true},
  {id:94,
    name:"Cadwy",
    role:"King",
    faction:"Summerset",
    status:"alive",
    pronoun:"He/him",
    misc:"King of Summerset. Owes nominal fealty to Uther. In 488 secretly agreed not to rebel while the British army was in France.",
    stats:"Suspicious 19 · Love (Summerset) · Intrigue 20 · Stewardship 18",
    playerVisible:false},
  {id:95,
    name:"Melwas",
    role:"Knight",
    faction:"Summerset",
    status:"alive",
    age:"41",
    glory:"13000",
    pronoun:"He/him",
    stats:"Proud 11 · Love (Glory) · Lance 16 · Tourney 16",
    playerVisible:false},
  {id:96,
    name:"Corneus",
    role:"Duke",
    faction:"Lindsey",
    status:"alive",
    age:"56",
    glory:"8400",
    stats:"Valorous 13 · Loyalty (Uther) · Battle 19 · Sword 15",
    playerVisible:false},
  {id:97,
    name:"Leri",
    role:"Youngest Daughter of Duke",
    faction:"Lindsey",
    status:"alive",
    age:"22",
    glory:"1500",
    misc:"Woman's Gift: Estimates wealth and class of any stranger at a glance",
    stats:"Modest 12 · Love (Family) · Stewardship 15 · Courtesy 13",
    playerVisible:false},
  {id:98,
    name:"Madog",
    role:"Castellan of Lincoln",
    faction:"Lindsey",
    status:"alive",
    age:"36",
    glory:"3400",
    stats:"Prudent 17 · Loyalty (Corneus) · Battle 17 · Stewardship 13",
    playerVisible:false},
  {id:99,
    name:"Sir Celyn",
    role:"Baron",
    faction:"Lindsey",
    status:"alive",
    misc:"Baron of Woodgrove (Linden).",
    stats:"Just 18 · Honor · Sword 20 · Heraldry 13",
    playerVisible:true},
  {id:100,
    name:"Lampades",
    role:"Abbot-Bishop",
    faction:"Lindsey",
    status:"alive",
    misc:"Abbot-bishop of Linden Pool (Linden). Baron of the Robe.",
    stats:"Spiritual 13 · Honor · Orate 14 · Stewardship 17",
    playerVisible:true},
  {id:101,
    name:"Heraut de Aupres",
    role:"King",
    faction:"Malahaut",
    status:"alive",
    age:"45",
    glory:"17800",
    stats:"Proud 16 · Love (Roman Legacy) · Battle 21 · Orate 14",
    playerVisible:false},
  {id:102,
    name:"Sygarius",
    role:"Praetor",
    faction:"Franklands",
    status:"alive",
    age:"36",
    glory:"8510",
    misc:"Last Roman Praetor of Gaul. In 488, knelt before Prince Madoc and begged him to march on Rouen to avenge his father's oath — was refused and rode off dumbfounded. Increasingly desperate for British support.",
    stats:"Proud 17 · Hate (King Claudas) · Orate 14 · Horsemanship 14",
    playerVisible:false},
  {id:103,
    name:"King Claudas",
    role:"King",
    faction:"Franklands",
    status:"alive",
    pronoun:"He/him",
    misc:"Frankish king and enemy of Britain. Court gossip in 488 says he has never lost a battle. A powerful antagonist driving the Frankland campaign.",
    stats:"Valorous 13 · Love (Victory) · Battle 16 · Sword 14",
    playerVisible:false},
  {id:104,
    name:"King Aelle",
    role:"",
    faction:"Saxon Shore",
    status:"alive",
    stats:"Valorous 12 · Hate (Britons) · Battle 17 · Sword 16",
    playerVisible:false},
  {id:105,
    name:"Cerdic",
    role:"",
    faction:"Saxon Shore",
    status:"alive",
    glory:"2663",
    misc:"King of Wessex. Warrior-king; father was High King Vortigern. Raised in Germany. Ambitious, dangerous. No lord. Home: Winchester. SIZ:16 DEX:12 STR:20 CON:10 Raides in Salisbury from time to time, APP:11 HP:26. Battle 15, Sword 18, Great Axe 13.",
    playerVisible:false},
  {id:106,
    name:"Saexwulf",
    role:"",
    faction:"Saxon Shore",
    status:"alive",
    glory:"7000",
    misc:"Saxon Aetheling. Hard-core, religiously conservative. Fearless, devoted to Wotan. Lord: Cerdic. Fights on foot. SIZ:20 DEX:10 STR:20 CON:17 APP:10 HP:37. Battle 21, Sword 23, Great Axe 19, Axe 23.",
    playerVisible:false},
  {id:107,
    name:"Earl Robert",
    role:"Earl",
    faction:"Saxon Shore",
    status:"alive",
    pronoun:"He/him",
    misc:"British commander in the France campaign of 488. His force waited at Bayeaux during the assault. Details otherwise unknown.",
    stats:"Just 13 · Loyalty (Uther) · Battle 15 · Heraldry 20",
    playerVisible:false},
  {id:108,
    name:"Sir Auryn",
    role:"Baron",
    faction:"Ascalon",
    status:"alive",
    misc:"Baron of the Roaring Stream (Ascalon).",
    stats:"Prudent 19 · Honor · Sword 17 · Awareness 11",
    playerVisible:true},
  {id:109,
    name:"Sir Sulien",
    role:"Count",
    faction:"Bedegraine",
    status:"alive",
    misc:"Count Bedegraine. Baron of Field of Doves (Bedegraine), Castle on Shining Stream (Jagent). Newly defeated, now loyal to Uther.",
    stats:"Forgiving 14 · Loyalty (Uther, new) · Battle 17 · Orate 11",
    playerVisible:true},
  {id:110,
    name:"Sir Gruffydd",
    role:"Baron",
    faction:"Berroc",
    status:"alive",
    misc:"Baron of the Roe Deer Gate (Berroc).",
    stats:"Suspicious 18 · Honor · Sword 18 · Heraldry 16",
    playerVisible:true},
  {id:111,
    name:"Sir Ganfael",
    role:"Baron",
    faction:"Caercolun",
    status:"alive",
    misc:"Baron of Hartspool (Caercolun).",
    stats:"Energetic 19 · Honor · Sword 14 · Battle 16",
    playerVisible:true},
  {id:112,
    name:"Sir Varwawc",
    role:"Baron",
    faction:"Caercolun",
    status:"alive",
    misc:"Baron of Southtown (Caercolun).",
    stats:"Generous 13 · Hospitality · Courtesy 19 · Stewardship 15",
    playerVisible:true},
  {id:113,
    name:"Dyfan",
    role:"Bishop",
    faction:"Caercolun",
    status:"alive",
    misc:"Bishop of Camulodunum (Caercolun), Lord of New Works Castle (Linden). Baron of the Robe.",
    stats:"Spiritual 20 · Honor · Orate 21 · Intrigue 21",
    playerVisible:true},
  {id:114,
    name:"Lady Blodeyn",
    role:"Baroness",
    faction:"Caerwent",
    status:"alive",
    misc:"Baroness of the Castle at the Crossing (Caerwent).\nWoman's Gift: Can navigate any river or coastal approach from memory",
    stats:"Valorous 14 · Honor · Sword 14 · Stewardship 18",
    playerVisible:true},
  {id:115,
    name:"Lady Pomponia",
    role:"Baroness",
    faction:"Caerwent",
    status:"alive",
    misc:"Baroness of Clareia (Caerwent), the Sand Dunes (Silchester), Custos of Duke of the Saxon Shore.\nWoman's Gift: Identifies ambition in others before they know it themselves",
    stats:"Selfish 17 · Love (Sir Lucius) · Intrigue 16 · Stewardship 18",
    playerVisible:true},
  {id:116,
    name:"Sir Lucius",
    role:"Duke of the Saxon Shore",
    faction:"Caerwent",
    status:"alive",
    glory:"1897",
    misc:"Duke of the Saxon Shore (inherits title in 484). Glory 897 + 1000 when knighted in 483. Scion of distinguished Roman family with broad imperial-era lands. Knighted prematurely by scheming courtiers led by aunt Baroness Pomponia. Father's favourite Marvis de Revil is Seneschal of Caercolun while king's officers manage other estates during his youth. Baron of Fort Bran (Caerwent), Seafort (Caerwent), Old Fort (Caerwent), Fort Brutus (Caercolun), Broadstream Fort (Caerwent), Harborkeep (Hantonne), Buna's Island (Caercolun).",
    stats:"Proud 17 · Love (Roman Heritage) · Orate 19 · Stewardship 16",
    playerVisible:true},
  {id:117,
    name:"Andronicus",
    role:"Bishop",
    faction:"Caerwent",
    status:"alive",
    misc:"Bishop of Venta (Caerwent). Baron of the Robe.",
    stats:"Just 18 · Honor · Orate 16 · Courtesy 15",
    playerVisible:true},
  {id:118,
    name:"Lady Sulwyn",
    role:"Baroness",
    faction:"Clarence",
    status:"alive",
    misc:"Baroness of the Hidden Vale (Clarence).\nWoman's Gift: Her household never runs short — she wastes nothing",
    stats:"Generous 19 · Hospitality · Stewardship 21 · Courtesy 16",
    playerVisible:true},
  {id:119,
    name:"Decius",
    role:"Bishop",
    faction:"Clarence",
    status:"alive",
    misc:"Bishop of Corinium (Clarence), Lord of Hawthorn (Caercolun). Baron of the Robe.",
    stats:"Spiritual 17 · Honor · Orate 18 · Intrigue 13",
    playerVisible:true},
  {id:120,
    name:"Sir Kynon",
    role:"Baron",
    faction:"Dorsette",
    status:"alive",
    misc:"Baron of Meadowstream (Dorsette).",
    stats:"Energetic 14 · Honor · Sword 18 · Hunting 20",
    playerVisible:true},
  {id:121,
    name:"Sir Tegwared",
    role:"Baron",
    faction:"Dorsette",
    status:"alive",
    misc:"Baron of Weir Meadow (Dorsette).",
    stats:"Prudent 16 · Loyalty (Uther) · Battle 17 · Stewardship 17",
    playerVisible:true},
  {id:122,
    name:"Mesalla",
    role:"Bishop",
    faction:"Dorsette",
    status:"alive",
    misc:"Bishop of Durnovaria (Dorsette), Lord of Middlestone (Rydychan). Baron of the Robe.",
    stats:"Just 18 · Honor · Orate 17 · Courtesy 16",
    playerVisible:true},
  {id:123,
    name:"Sir Dryw",
    role:"Baron",
    faction:"Gentian",
    status:"alive",
    misc:"Baron of Sparrowhawk Castle (Gentian).",
    stats:"Suspicious 17 · Honor · Sword 21 · Awareness 17",
    playerVisible:true},
  {id:124,
    name:"Cadfael",
    role:"Abbot",
    faction:"Gentian",
    status:"alive",
    misc:"Abbot of Bladud's Mound Abbey, Lord of Bladud's Mound (Gentian). Baron of the Robe.",
    stats:"Spiritual 12 · Love (Gentian, his abbey) · Orate 18 · Stewardship 13",
    playerVisible:true},
  {id:125,
    name:"Sir Eldol",
    role:"Duke of Glevum",
    faction:"Glevum",
    status:"alive",
    age:"100",
    glory:"19067",
    misc:"Duke of Glevum. Age 100+ in 480, Glory 19067. Notable: Homage (Uther) 15, Loyalty (Britain) 18, Hate (Saxons) 18, Courtesy 10, Battle 22. Only survivor of the Night of Long Knives when Saxons treacherously murdered British nobles. Rumoured to be over 100 years old in 480. Heirs already feuding over inheritance. Baron of Goodrich (Glevum), Birchwood (Clarence), Stoneheight Castle (Tribruit), Bees Clearing (Ascalon), Hillfarm (Salisbury).",
    playerVisible:true},
  {id:126,
    name:"Sir Gwenwynwyn",
    role:"Baron",
    faction:"Hantonne",
    status:"alive",
    misc:"Baron of the Island that was Raised (Hantonne), Lord of Yarmouth Fort.",
    stats:"Valorous 12 · Hate (Saxons) · Boating 12 · Sword 18",
    playerVisible:true},
  {id:127,
    name:"Sir Bassianus",
    role:"Baron",
    faction:"Hantonne",
    status:"alive",
    misc:"Baron of Noviomagus (Hantonne). Rich baron; presides over old Roman city secure against Saxons.",
    stats:"Prudent 14 · Love (Noviomagus) · Stewardship 19 · Intrigue 16",
    playerVisible:true},
  {id:128,
    name:"Sir Lleufer",
    role:"Baron",
    faction:"Hantonne",
    status:"alive",
    misc:"Baron of the Roman Isle (Hantonne).",
    stats:"Energetic 21 · Honor · Boating 17 · Sword 15",
    playerVisible:true},
  {id:129,
    name:"Cynfarch",
    role:"Abbot-Bishop",
    faction:"Hartland",
    status:"alive",
    misc:"Abbot-bishop of St Albans, Lord of St Albans (Hartland) and Saffron (Hartland). Baron of the Robe.",
    stats:"Spiritual 17 · Love (St Albans) · Orate 16 · Stewardship 14",
    playerVisible:true},
  {id:130,
    name:"Sir Madern",
    role:"Baron",
    faction:"Jagent",
    status:"alive",
    misc:"Baron of Castle of the Pinnacle (Jagent).",
    stats:"Prudent 13 · Honor · Sword 20 · Awareness 14",
    playerVisible:true},
  {id:131,
    name:"Earl of Jagent",
    role:"Earl",
    faction:"Jagent",
    status:"alive",
    pronoun:"He/him",
    family:"Jagent",
    misc:"Regional lord of Jagent. Joined the southern forces marching to embark for Frankland in 488.",
    stats:"Valorous 16 · Loyalty (Uther) · Battle 14 · Lance 15",
    playerVisible:false},
  {id:132,
    name:"Sir Cadawg",
    role:"Baron",
    faction:"Lambor",
    status:"alive",
    misc:"Baron of the Beautiful View (Lambor). Castle guards border with Cameliard.",
    stats:"Prudent 20 · Love (Cameliard border) · Battle 19 · Awareness 16",
    playerVisible:true},
  {id:133,
    name:"Sir Gynnfardd",
    role:"Baron",
    faction:"Lambor",
    status:"alive",
    misc:"Baron of the Horsemane Fort (Lambor).",
    stats:"Energetic 20 · Honor · Lance 18 · Horsemanship 18",
    playerVisible:true},
  {id:134,
    name:"Sir Anian",
    role:"Baron",
    faction:"Lambor",
    status:"alive",
    misc:"Baron of Stonetown Castle (Lambor).",
    stats:"Just 17 · Honor · Sword 17 · Orate 14",
    playerVisible:true},
  {id:135,
    name:"Sir Edaris",
    role:"Duke of the Marche",
    faction:"Lambor",
    status:"alive",
    age:"47",
    glory:"8778",
    misc:"Duke of the Marche. Age 47, Glory 8778 in 480. Notable: Homage (Uther) 22, Hate (Cambrians) 17, Courtesy 15, Battle 19. Father killed by Cambrian raiders in 479; Edaris inherits in 480 and has not forgiven nor forgotten. Baron of Leir's Castle (Lambor), Bow and Arrow Castle (Dorsette), Humberside (Linden), Stonewall (Tribruit), Bran's Town (Lambor), Ashtree Spring (Hartland).",
    playerVisible:true},
  {id:136,
    name:"Sir Emyr",
    role:"Baron",
    faction:"Lonazep",
    status:"alive",
    misc:"Baron of Castle Behind the Waters (Lonazep). Keeps watch on island between the Fens and the German Sea.",
    stats:"Trusting 18 · Honor · Boating 18 · Sword 17",
    playerVisible:true},
  {id:137,
    name:"Sir Galehaut",
    role:"Baron of Castle Brown",
    faction:"Lonazep",
    status:"alive",
    age:"48",
    glory:"8284",
    misc:"Baron of Castle on the Water (Lonazep), also called Castle Brown (Brun). Glory 8284 (Famous). Age 48 in 480. Appearance: Big, tough. Personality: Patient, blunt. Type: Combatant. Notable: Valorous 19, Homage (Uther) 18, Battle 16, Spear Expertise 23. Third-born son of Sir Ellain the Brown; close friend of Sir Argan. Big, tough, brown hair, blue eyes, full beard, slight limp. Black chain mail polished to mirror finish. Father of Sir Dinadan and La cote mal taillée.",
    playerVisible:true},
  {id:138,
    name:"Sir Segurant",
    role:"Household Knight of Castle Brun",
    faction:"Lonazep",
    status:"alive",
    age:"31",
    glory:"10211",
    misc:"Sir Segurant the Brown. Household Knight of Castle Brun. Glory 10211 (Famous), Age 31 in 480. Appearance: Big and Strong. Personality: Hedonist hero. Type: Combatant. Notable: APP 16, Energetic 20, Lustful 16, Valorous 20, Hunting 17, Spear Expertise 23, Sword 23. Grandson of Sir Hector the Brown; proud of Brun family heritage, armour coloured brown. Called 'Knight of the Dragon' for hunting a monster ravaging various lands. Tall, strong, handsome; uses dark eyes and luxurious hair to charm.",
    playerVisible:true},
  {id:139,
    name:"Sir Arnoullant",
    role:"Household Knight of Castle Brun",
    faction:"Lonazep",
    status:"alive",
    age:"35",
    glory:"16510",
    misc:"Sir Arnoullant the Fair. Household Knight of Castle Brun. Glory 16510 (Extraordinary), Age 35 in 480. Appearance: Big and Strong. Personality: Restless, cheerful. Type: Adventurer. Notable: APP 18, Energetic 18, Reckless 16, Valorous 20, Spear Expertise 22, Sword 23. Boon companion of Segurant the Brown. Large man with blonde hair, blue eyes, neatly trimmed beard; famously handsome, face unmarred by scars. Relentless Glory seeker, travels far slaying giants and monsters. Slain and devoured by a dragon in 495.",
    playerVisible:true},
  {id:140,
    name:"Sir Meliodas",
    role:"Foreign Visitor",
    faction:"Lyonesse",
    status:"alive",
    age:"25",
    glory:"5849",
    misc:"Sir Meliodas of Lyonesse. Foreign Visitor. Glory 5849 (Renowned), Age 25 in 480. Appearance: Big and Strong. Personality: Lawful Hero. Type: Courtier. Notable: Honest 16, Just 18, Courtesy 18, Orate 16, Great Axe 18, Lance 17, Sword 17. Younger son of Felec, King of Lyonesse; set adrift to make his own fortune. Will become King of Lyonesse and father of Sir Tristram. Marries Elyabel, sister of Prince Mark of Cornwall. Brown hair, squinty brown eyes, growing beard, youthful look.",
    playerVisible:true},
  {id:141,
    name:"Sir Tarrant",
    role:"Baron",
    faction:"Thamesmouth",
    status:"alive",
    misc:"Baron of the Chattering Glade (Thamesmouth).",
    stats:"Suspicious 16 · Honor · Sword 16 · Awareness 14",
    playerVisible:true},
  {id:142,
    name:"Palladius",
    role:"Abbot",
    faction:"Thamesmouth",
    status:"alive",
    misc:"Abbot of Westminster Abbey (Thamesmouth), Lord of Aneirin (Thamesmouth) and Woodland (Silchester). Baron of the Robe.",
    stats:"Spiritual 15 · Love (Westminster) · Orate 17 · Stewardship 12",
    playerVisible:true},
  {id:143,
    name:"Quintus",
    role:"Bishop",
    faction:"Thamesmouth",
    status:"alive",
    misc:"Bishop of Londinium (Thamesmouth), Lord of Birch Hill (Rydychan) and Grantabridge. Baron of the Robe.",
    stats:"Just 13 · Honor · Orate 19 · Intrigue 17",
    playerVisible:true},
  {id:144,
    name:"Sir Elystan",
    role:"Baron",
    faction:"Tribruit",
    status:"alive",
    misc:"Baron of the Dangerous Ford (Tribruit).",
    stats:"Valorous 12 · Honor · Sword 17 · Awareness 17",
    playerVisible:true},
  {id:145,
    name:"Sir Cynfan",
    role:"Baron",
    faction:"Tribruit",
    status:"alive",
    misc:"Baron of Castle Dykes (Tribruit).",
    stats:"Energetic 17 · Honor · Lance 12 · Sword 17",
    playerVisible:true},
  {id:146,
    name:"Sir Pwyll",
    role:"Baron",
    faction:"Tribruit",
    status:"alive",
    misc:"Baron of Goat Town (Tribruit).",
    stats:"Generous 20 · Hospitality · Courtesy 15 · Sword 17",
    playerVisible:true},
  {id:147,
    name:"Sir Meneu",
    role:"Baron",
    faction:"Tribruit",
    status:"alive",
    misc:"Baron of Rooksroost (Tribruit).",
    stats:"Prudent 13 · Honor · Sword 16 · Stewardship 18",
    playerVisible:true},
  {id:148,
    name:"Sir Collen",
    role:"Baron",
    faction:"Tribruit",
    status:"alive",
    misc:"Baron of Sentinel Ridge (Tribruit).",
    stats:"Suspicious 21 · Honor · Sword 19 · Awareness 15",
    playerVisible:true},
  {id:149,
    name:"Sir Cadel",
    role:"Baron",
    faction:"Wuerensis",
    status:"alive",
    misc:"Baron of the Cattleherds (Wuerensis).",
    stats:"Energetic 14 · Honor · Sword 17 · Heraldry 14",
    playerVisible:true},
  {id:150,
    name:"Sir Landri",
    role:"Baron",
    faction:"Wuerensis",
    status:"alive",
    misc:"Baron of Slayersfort (Wuerensis).",
    stats:"Valorous 18 · Hate (Enemies of Wuerensis) · Battle 19 · Sword 17",
    playerVisible:true},
  {id:151,
    name:"Sir Ederyn",
    role:"Baron",
    faction:"Wuerensis",
    status:"alive",
    misc:"Baron of Warcastle (Wuerensis), Castle of Vigor (Caercolun), Estate of the Extraordinary Cattle (Caercolun), Brothercross Estate (Caerwent). Rich baron.",
    stats:"Selfish 15 · Love (Wealth) · Stewardship 19 · Intrigue 14",
    playerVisible:true},
  {id:152,
    name:"Sir Amren",
    role:"Baron",
    faction:"Wuerensis",
    status:"alive",
    misc:"Baron on the Lonely Path (Wuerensis).",
    stats:"Trusting 19 · Honor · Sword 16 · Courtesy 16",
    playerVisible:true},
  {id:153,
    name:"Nineve",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Lady of the Lake.\nWoman's Gift: Sees the true nature of magical objects",
    stats:"Prudent 15 · Love (The Lake) · Faerie Lore 15 · Intrigue 13",
    playerVisible:false},
  {id:154,
    name:"Guenevere",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Princess, future High Queen.\nWoman's Gift: Her presence raises the courage of those around her",
    stats:"Just 16 · Love (Arthur, future) · Courtesy 15 · Intrigue 15",
    playerVisible:false},
  {id:155,
    name:"Carados",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"King of Escoce.",
    stats:"Proud 16 · Hate (Saxons) · Battle 16 · Sword 14",
    playerVisible:false},
  {id:156,
    name:"Lot",
    role:"King of Lothian and Orkney",
    faction:"Other",
    status:"alive",
    misc:"King of Lothian and Orkney. A powerful but ambitious northern ally of Uther.",
    stats:"Ambitious 16 · Love (Power) · Battle 15 · Intrigue 14",
    playerVisible:false},
  {id:157,
    name:"Nimue",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Lady of the Lake.\nWoman's Gift: Can breathe underwater and never fears drowning",
    stats:"Prudent 16 · Love (The Lake) · Faerie Lore 16 · Awareness 12",
    playerVisible:false},
  {id:158,
    name:"Viviane",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Lady of the Lake.\nWoman's Gift: Her voice carries visions — listeners see what she describes",
    stats:"Mysterious 12 · Love (The Lake) · Faerie Lore 16 · Orate 13",
    playerVisible:false},
  {id:159,
    name:"Palomides",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Saracen knight of the Round Table.",
    stats:"Valorous 19 · Love (Iseult, tragically) · Sword 15 · Tourney 15",
    playerVisible:false},
  {id:160,
    name:"Constantine",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"King of Cornwall, successor to Arthur.",
    stats:"Just 18 · Loyalty (Britain) · Battle 14 · Orate 19",
    playerVisible:false},
  {id:161,
    name:"Brian",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Lord of the Isles.",
    stats:"Energetic 21 · Love (The Isles) · Boating 12 · Sword 13",
    playerVisible:false},
  {id:162,
    name:"Constantine (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Successor to Arthur (Twilight Period).",
    stats:"Just 15 · Loyalty (Britain) · Battle 17 · Orate 19",
    playerVisible:false},
  {id:163,
    name:"Kay",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Arthur's foster-brother and Seneschal.",
    stats:"Proud 19 · Love (Arthur) · Stewardship 12 · Orate 20",
    playerVisible:false},
  {id:164,
    name:"Lancelot",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Greatest knight of the Round Table.",
    stats:"Valorous 17 · Love (Round Table) · Lance 16 · Sword 18",
    playerVisible:false},
  {id:165,
    name:"Gawaine",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table, Arthur's nephew.",
    stats:"Valorous 15 · Loyalty (Arthur) · Sword 15 · Hunting 17",
    playerVisible:false},
  {id:166,
    name:"Arthur",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High King of Britain.",
    stats:"Just 19 · Love (Britain) · Battle 13 · Orate 20",
    playerVisible:false},
  {id:167,
    name:"Queen Guenevere",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High Queen of Britain.\nWoman's Gift: Inspires absolute devotion — those who serve her would die without question",
    stats:"Generous 13 · Love (Arthur) · Courtesy 17 · Intrigue 14",
    playerVisible:false},
  {id:168,
    name:"Borre",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table, son of Arthur.",
    stats:"Energetic 18 · Loyalty (Arthur) · Lance 19 · Sword 15",
    playerVisible:false},
  {id:169,
    name:"Lamorak",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table.",
    stats:"Valorous 17 · Love (Glory) · Lance 20 · Tourney 17",
    playerVisible:false},
  {id:170,
    name:"Loholt",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur.",
    stats:"Reckless 18 · Loyalty (Arthur) · Sword 17 · Hunting 20",
    playerVisible:false},
  {id:171,
    name:"Mordred",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur and Morgawse.",
    stats:"Vengeful 15 · Hate (Arthur) · Intrigue 12 · Sword 16",
    playerVisible:false},
  {id:172,
    name:"Dinadin",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table.",
    stats:"Temperate 15 · Love (Chivalry) · Orate 19 · Courtesy 19",
    playerVisible:false},
  {id:173,
    name:"Galahad",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Perfect knight, son of Lancelot.",
    playerVisible:false},
  {id:174,
    name:"Bors",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table.",
    stats:"Valorous 13 · Loyalty (Arthur) · Lance 16 · Sword 15",
    playerVisible:false},
  {id:175,
    name:"Percivale",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table.",
    stats:"Spiritual 14 · Love (Grail Quest) · Faerie Lore 15 · Sword 17",
    playerVisible:false},
  {id:176,
    name:"Lavaine",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table.",
    stats:"Trusting 18 · Loyalty (Lancelot) · Lance 15 · Sword 16",
    playerVisible:false},
  {id:177,
    name:"Urre",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Hungarian knight healed by Lancelot.",
    playerVisible:false},
  {id:178,
    name:"Arthur (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High King of Britain (Tournament Period).",
    stats:"Just 12 · Love (Britain) · Battle 19 · Orate 18",
    playerVisible:false},
  {id:179,
    name:"Arthur (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High King of Britain (Twilight Period).",
    stats:"Just 17 · Love (Britain) · Battle 19 · Orate 19",
    playerVisible:false},
  {id:180,
    name:"Borre (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur (Tournament Period).",
    stats:"Energetic 14 · Loyalty (Arthur) · Lance 13 · Sword 15",
    playerVisible:false},
  {id:181,
    name:"Gawaine (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Arthur's nephew (Twilight Period).",
    stats:"Valorous 17 · Loyalty (Arthur) · Sword 18 · Hunting 17",
    playerVisible:false},
  {id:182,
    name:"Kay (40)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Arthur's Seneschal (Tournament Period).",
    stats:"Proud 18 · Love (Arthur) · Stewardship 17 · Orate 19",
    playerVisible:false},
  {id:183,
    name:"Lamorak (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Knight of the Round Table (Tournament Period).",
    stats:"Valorous 17 · Love (Glory) · Lance 18 · Tourney 16",
    playerVisible:false},
  {id:184,
    name:"Lancelot (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Greatest knight (Tournament Period).",
    stats:"Valorous 15 · Love (Round Table) · Lance 12 · Sword 17",
    playerVisible:false},
  {id:185,
    name:"Lancelot (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Greatest knight (Twilight Period).",
    stats:"Valorous 13 · Love (Round Table) · Lance 20 · Sword 17",
    playerVisible:false},
  {id:186,
    name:"Loholt (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur (Tournament Period).",
    stats:"Reckless 13 · Loyalty (Arthur) · Sword 19 · Hunting 18",
    playerVisible:false},
  {id:187,
    name:"Mordred (540)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur (Tournament Period).",
    stats:"Vengeful 19 · Hate (Arthur) · Intrigue 17 · Sword 12",
    playerVisible:false},
  {id:188,
    name:"Mordred (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"Son of Arthur (Twilight Period).",
    stats:"Vengeful 14 · Hate (Arthur) · Intrigue 14 · Sword 13",
    playerVisible:false},
  {id:189,
    name:"Queen Guenevere (40)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High Queen (Tournament Period).\nWoman's Gift: Inspires absolute devotion",
    stats:"Generous 20 · Love (Arthur) · Courtesy 14 · Intrigue 11",
    playerVisible:false},
  {id:190,
    name:"Queen Guenevere (558)",
    role:"",
    faction:"Other",
    status:"alive",
    misc:"High Queen (Twilight Period).\nWoman's Gift: Inspires absolute devotion",
    stats:"Generous 17 · Love (Arthur) · Courtesy 17 · Intrigue 19",
    playerVisible:false},
];
